server:
  port: ${PROT:16001}
spring:
  application:
    name: miracle-service-order
  datasource:
    druid:
      url: ${MYSQL_URL:jdbc:mysql://localhost:3306/miracle_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      initial-size: 5
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  #---rabbitmq---
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    publisher-confirms: true
    listener:
      simple:
        #指定最小的消费者数量
        concurrency: 1
        max-concurrency: 2
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 2
          initial-interval: 2000
      direct:
      #开启ack
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 2
    #支持消息的确认与返回
    template:
      mandatory: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service_url:
        defaultZone: ${EUREKA_SERVER:http://127.0.0.1:10001/eureka,http://127.0.0.1:10002/eureka}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000
  instance:
    prefer-ip-address: true
    hostname: localhost
# ---miracle---
miracle:
  work:
    workerId: 1
    dataCenterId: 2