server:
  port: ${PROT:10001}
spring:
  application:
    name: miracle-govern-register
  security:
    user:
      name: admin
      password: 12345
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 30
    service_url:
        defaultZone: ${EUREKA_SERVER:http://admin:12345@127.0.0.1:10002/eureka}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000
  instance:
    prefer-ip-address: true
    hostname: localhost

