server:
  port: 11001
spring:
  application:
    name: miracle-service-manage-user
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  transaction:
    rollback-on-commit-failure: true
  datasource:
    druid:
      url: ${MYSQL_URL:jdbc:mysql://localhost:3306/miracle_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai}
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://admin:12345@127.0.0.1:10001/eureka,http://admin:12345@127.0.0.1:10002/eureka}
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} #指定实例id
    lease-renewal-interval-in-seconds: 10 #Client发给Server的心跳频率
    lease-expiration-duration-in-seconds: 10 #Server收到上一次心跳时间之后，等待下一次心跳的超时时间。如果在时间内没有收到，则进行服务剔除

miracle:
  work:
    workerId: 1
    dataCenterId: 1
#---redisson---
#集群模式
#redisson:
#  client-name: myclient
#  password:
#  node-addresses: redis://192.168.1.103:7000,redis://192.168.1.103:7001,redis://192.168.1.103:7002,redis://192.168.1.103:7003,redis://192.168.1.103:7004,redis://192.168.1.103:7005
redisson:
  address: redis://106.12.150.85:6789
  password: ai_redis